ASPMVCTrial/Controllers/DealController.cs
using ASPMVCTrial.Data.Interfaces;
using ASPMVCTrial.Models;
using ASPMVCTrial.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ASPMVCTrial.Controllers
{
    public class DealController : Controller
    {
        private readonly IDealService dealService;
        private readonly IPhotoService photoService;

        public DealController(IDealService _dealService, IPhotoService _photoService)
        {
            dealService = _dealService;
            photoService = _photoService;
        }

        public async Task<IActionResult> Index()
        {
            var deals = await dealService.GetAll();
            return View(deals);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewDealViewModel dealViewModel)
        {
            if (!ModelState.IsValid) return View(dealViewModel);

            var addedPhoto = await photoService.AddPhotoAsync(dealViewModel.Image);

            var deal = new Deal
            {
                Amount = dealViewModel.Amount,
                Partner = dealViewModel.Partner,
                Profit = dealViewModel.Profit,
                ComissionCash = dealViewModel.ComissionCash,
                ComissionPercent = dealViewModel.ComissionPercent,
                Image = addedPhoto.Url.ToString()
            };

            var added = dealService.Add(deal);

            if (!added) return View("Error");

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var deal = await dealService.GetById(id);

            if (deal == null) return View("Error");

            return View(deal);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteDeal(int id)
        {
            var deal = await dealService.GetById(id);

            if (deal == null) return View("Error");

            var deleted = dealService.Delete(deal);

            if (!deleted) return View("Error");

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var deal = await dealService.GetById(id);

            if (deal == null) return View("Error");

            var dealVM = new EditDealViewModel
            {
                Id = id,
                Amount = deal.Amount,
                Partner = deal.Partner,
                Profit = deal.Profit,
                ComissionCash = deal.ComissionCash,
                ComissionPercent = deal.ComissionPercent,
                URL = deal.Image
            };

            return View(dealVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditDealViewModel dealVM)
        {
            if (!ModelState.IsValid) return View(dealVM);

            var deal = await dealService.GetByIdNoTracking(dealVM.Id);

            if (deal == null) return View("Error");

            var editPhoto = await photoService.AddPhotoAsync(dealVM.Image);

            if (editPhoto.Error != null) return View(dealVM);

            if (!string.IsNullOrEmpty(deal.Image))
            {
                _ = photoService.DeletePhotoAsync(deal.Image);
            }

            var newDeal = new Deal
            {
                Id = dealVM.Id,
                Amount = dealVM.Amount,
                Partner = dealVM.Partner,
                Profit = dealVM.Profit,
                ComissionCash = dealVM.ComissionCash,
                ComissionPercent = dealVM.ComissionPercent,
                Image = editPhoto.Url.ToString()
            };

            dealService.Update(newDeal);

            return RedirectToAction("Index");
        }
    }
}

ASPMVCTrial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPMVCTrial</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPMVCTrial.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Deal" asp-action="Index">ASPMVCTrial</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Deal" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <form asp-action="Logout" asp-controller="Account">
                                    <button class="btn btn-outline-danger">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>